version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: typing_game
    volumes:
      - ${PWD}/db:${PWD}/db
  redis:
    image: redis:2.8
    ports:
      - '6379:6379'
